### PR TITLE
Update big-data.md

### PR DESCRIPTION
**Pull request by TingtingYiTina**
update

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by ticianaciminari** [comment]
Hello, @TingtingYiTina , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by LisandroSu** [comment]
Hello, @TingtingYiTina 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Pull request merged**
